#!/bin/bash
# Author: Bora Hamarat
# Date: 02.08.2024
# Description: Backup /etc and /var fileystem
remote_user="bora"
sudo tar cvf /tmp/backup.tar /etc /var
sudo gzip /tmp/backup.tar
find /tmp/backup.tar.gz -mtime -1 -type f -print &> /dev/null
if [ $? -eq 0 ]
then
	echo Backup was created
	echo 
	echo Archiving Backup
	scp /tmp/backup.tar.gz root@192.168.1.35:/home/${remote_user}/
else
	echo Backup Failed
fi
