#!/bin/bash
# Author: Bora Hamarat
# Date: 02.08.2024
# Description: check the existence of files
FILES="/etc/passwd
/etc/group
/etc/shadow
/etc/nsswitch.conf
/etc/sshd_ssh_config
/etc/fake"
for file in $FILES
do
	if [ ! -e $file ]
	then
		echo $file does not exist
	fi
done
