#!/bin/bash 
# Author: Bora Hamarat
# Date: 02.08.2024
# Description: This script performs a complete cleanup of a specified LVM setup and associated partition on an Ubuntu machine.
lv_name="oracle_lv"
vg_name="oracle_vg"
sudo umount /dev/mapper/${vg_name}-${lv_name}
sudo lvchange -an /dev/${vg_name}/${lv_name}
sudo lvremove /dev/${vg_name}/${lv_name}
sudo vgremove ${vg_name}
sudo pvremove /dev/sdb1
sudo fdisk /dev/sdb
sudo reboot
